[workspace]
members = [
   "lib/main", # Main modding library crate
   "lib/proc", # Procedural macros incorporated into nusion
   "lib/sys",  # System abstractions used by nusion

   "game/*"       # Game-specific framework implementations
]

