[workspace]
members = [
   "lib/nusion-core",      # Main modding library crate
   "lib/nusion-core-proc", # Procedural macros incorporated into nusion-core
   "lib/nusion-core-sys",  # System abstractions used by nusion-core

   "game/*"                # Game-specific framework implementations
]

