[package]
name        = "nusion-game-drg"
description = "Nusion modding API for Deep Rock Galactic."
authors     = ["Sinisig"]
version     = "0.0.1+alpha"
edition     = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nusion = { path = "../../lib/main" }
lazy_static = "1.4.0"

